### ISSUE TITLE
Version 1.0.8 is not compatible with Chrome 84 on Debian

### ISSUE THREAD

**Issue by fredrikgiang** [flotwig/cypress-log-to-output#12]
I get the following warning when using cypress-log-to-output with Chrome 84 on Debian:
`[cypress-log-to-output] Warning: An unsupported browser family was used, output will not be logged to console: undefined`

Command using to run the tests:
`yarn cypress run --headless --browser chrome`

yarn cypress info:
1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 84.0.4147.89
  - Executable: google-chrome

Cypress version 4.10.0

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch

**Comment by fredrikgiang** [comment]
Same issue with Cypress version 4.11.0

**Comment by flotwig** [comment]
Does it work on any Cypress version?

**Comment by fredrikgiang** [comment]
Ops...I just realized I added code in plugin/index.js awhile ago that broke this plugin.
