### ISSUE TITLE
TypeError: Cannot read property 'recordLogs' of undefined

### ISSUE THREAD

**Issue by colinbr96** [flotwig/cypress-log-to-output#13]
**Version:** v1.1.0

**Bug Summary:**
The Usage section of the README states that the plugin should be installed via:
`require('cypress-log-to-output').install(on)`

However, this will cause a crash due to `options` not being passed to `install`. It appears `install` is written with the expectation that `options` is passed as an object:
```javascript
function install(on, filter, options) {
  eventFilter = filter;
  recordLogs = options.recordLogs; // TypeError: Cannot read property 'recordLogs' of undefined
  on('before:browser:launch', browserLaunchHandler)
}
```

**Workaround**
Install the plugin via: `require('cypress-log-to-output').install(on, undefined, {})`

**Comment by ldeveber** [comment]
We are also seeing this

**Comment by flotwig** [comment]
Please try upgrading to v1.1.1, where this has been fixed
