### ISSUE TITLE
Extraneous output

### ISSUE THREAD

**Issue by fr0** [flotwig/cypress-log-to-output#8]
Thanks for the useful plugin. It's very helpful.

I noticed that there are some extra lines that print out that I don't seem to have any control over:

```
 [cypress-log-to-output] Attempting to connect to Chrome Debugging Protocol
 [cypress-log-to-output] Connected to Chrome Debugging Protocol
 ...
 [cypress-log-to-output] Chrome Debugging Protocol disconnected    
```

These lines are just noise to me; is there a way for me  to filter them out?

**Comment by flotwig** [comment]
Released in 1.0.8: https://github.com/flotwig/cypress-log-to-output#disabling-debug-info
